apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: angular
    kyma-grafana: enabled
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: angular
        kyma-grafana: enabled
    spec:
      containers:
        - image: amirafathy/hostimg4
          name: hostcon4
          ports:
            - containerPort: 4200
          envFrom:
            - secretRef:
                name: angular
                optional: true
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: angular
  name: hostser4
spec:
  ports:
    - port: 4200
      name: http
      protocol: TCP
      targetPort: 4200
  selector:
    app: angular
  type: ClusterIP
status:
  loadBalancer: {}